const CONSTANTS = {};

CONSTANTS.ERROR_MESSAGE = {};

CONSTANTS.ERROR_MESSAGE.GRID_GET = "Request to get grid text failed:";

CONSTANTS.ENDPOINT = {};

CONSTANTS.ENDPOINT.GRID = "/api/grid";
CONSTANTS.ENDPOINT.LOGIN = "/user/login";
CONSTANTS.ENDPOINT.REGISTER = "/user/register";
CONSTANTS.ENDPOINT.UPLOAD = "/upload/postupload";
CONSTANTS.ENDPOINT.ADDPARTNER = "/";

CONSTANTS.ENDPOINT.USER = "/user";
CONSTANTS.ENDPOINT.CONTRACT = "/contract";
CONSTANTS.ENDPOINT.MAIL = "/mail";
CONSTANTS.ENDPOINT.VERIFY = "/verify/invite/203660";
export default CONSTANTS;
